import type { ICaptionStyleService } from './interface'
import type { StylePreset } from './types'

const MOCK_PRESETS: StylePreset[] = [
  {
    id: 'preset_1',
    name: 'Clean White',
    category: 'modern',
    style: {
      fontSize: 24,
      fontFamily: 'Inter',
      fontWeight: '600',
      fontStyle: 'normal',
      textDecoration: 'none',
      fontColor: '#FFFFFF',
      backgroundColor: '#00000080',
      strokeColor: '#000000',
      strokeWidth: 1,
      shadowColor: '#000000',
      shadowBlur: 4,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      opacity: 1,
      lineHeight: 1.4,
      letterSpacing: 0,
      textAlign: 'center',
      position: 'bottom',
      positionX: 50,
      positionY: 90,
      rotation: 0,
      scale: 1,
      animationPreset: null,
    },
  },
  {
    id: 'preset_2',
    name: 'Bold Impact',
    category: 'gaming',
    style: {
      fontSize: 32,
      fontFamily: 'Impact',
      fontWeight: '800',
      fontStyle: 'normal',
      textDecoration: 'none',
      fontColor: '#FFD700',
      backgroundColor: 'transparent',
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowColor: '#000000',
      shadowBlur: 6,
      shadowOffsetX: 2,
      shadowOffsetY: 2,
      opacity: 1,
      lineHeight: 1.2,
      letterSpacing: 1,
      textAlign: 'center',
      position: 'middle',
      positionX: 50,
      positionY: 50,
      rotation: 0,
      scale: 1.2,
      animationPreset: null,
    },
  },
  {
    id: 'preset_3',
    name: 'Subtle Dark',
    category: 'minimal',
    style: {
      fontSize: 18,
      fontFamily: 'Arial',
      fontWeight: '400',
      fontStyle: 'normal',
      textDecoration: 'none',
      fontColor: '#CCCCCC',
      backgroundColor: 'transparent',
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowBlur: 2,
      shadowOffsetX: 0,
      shadowOffsetY: 1,
      opacity: 0.9,
      lineHeight: 1.3,
      letterSpacing: 0.5,
      textAlign: 'center',
      position: 'bottom',
      positionX: 50,
      positionY: 92,
      rotation: 0,
      scale: 1,
      animationPreset: null,
    },
  },
  {
    id: 'preset_4',
    name: 'Classic Film',
    category: 'classic',
    style: {
      fontSize: 22,
      fontFamily: 'Georgia',
      fontWeight: '500',
      fontStyle: 'italic',
      textDecoration: 'none',
      fontColor: '#F5F5DC',
      backgroundColor: '#1a1a2e80',
      strokeColor: '#8B4513',
      strokeWidth: 1,
      shadowColor: '#8B4513',
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      opacity: 1,
      lineHeight: 1.5,
      letterSpacing: 0.3,
      textAlign: 'center',
      position: 'bottom',
      positionX: 50,
      positionY: 88,
      rotation: 0,
      scale: 1,
      animationPreset: null,
    },
  },
  {
    id: 'preset_5',
    name: 'Cinematic',
    category: 'cinematic',
    style: {
      fontSize: 28,
      fontFamily: 'Helvetica',
      fontWeight: '700',
      fontStyle: 'normal',
      textDecoration: 'none',
      fontColor: '#FFFFFF',
      backgroundColor: '#00000040',
      strokeColor: '#000000',
      strokeWidth: 0,
      shadowColor: '#000000',
      shadowBlur: 10,
      shadowOffsetX: 0,
      shadowOffsetY: 4,
      opacity: 1,
      lineHeight: 1.3,
      letterSpacing: 2,
      textAlign: 'center',
      position: 'bottom',
      positionX: 50,
      positionY: 85,
      rotation: 0,
      scale: 1,
      animationPreset: 'fade-in',
    },
  },
]

export class MockCaptionStyleService implements ICaptionStyleService {
  async getPresets(): Promise<StylePreset[]> {
    await new Promise((r) => setTimeout(r, 50))
    return MOCK_PRESETS.map((p) => ({ ...p, style: { ...p.style } }))
  }

  async getDefaultPreset(): Promise<StylePreset> {
    await new Promise((r) => setTimeout(r, 30))
    return { ...MOCK_PRESETS[0], style: { ...MOCK_PRESETS[0].style } }
  }
}
